#!/bin/bash
# Build script by: Luke Neville

# To run, ensure user has execute privileges and run ./build

if [ "$DBRDIR" == "" ]; then
DBRDIR=.
fi

DBRSRC=$DBRDIR/src
DBRBIN=$DBRDIR/bin
DBRTEST=$DBRDIR/test
LIB=/home/luke/Honours/Project/JavaDBR/lib
LIBJAR=$LIB/bin/:$LIB/jxl.jar:$LIB/log4j-core.jar:$LIB/log4j.jar:$LIB/metouia.jar:$LIB/mysql.jar:$LIB/ojdbc14_g.jar:$LIB/openjgraph.jar:$LIB/postgresql.jar:$LIB/skinlf.jar
DBRCLASSPATH=$DBRDIR:$LIBJAR
DBR=/edu/uct/dbr

javac -g:none -d $DBRBIN  -sourcepath $DBRSRC -cp $DBRCLASSPATH $DBRSRC/$DBR/*.java $DBRSRC/$DBR/gui/*.java $DBRSRC/$DBR/implication/*.java $DBRSRC/$DBR/util/*.java

javac -g:none -d $DBRBIN  -sourcepath $DBRSRC -cp $DBRCLASSPATH $DBRTEST/edu/uct/dbrtest/*.java 

