#!/bin/bash
# Build script by: Luke Neville

# To run, ensure user has execute privileges and run ./build

if [ "$IBRDIR" == "" ]; then
IBRDIR=.
fi

IBRSRC=$IBRDIR/src
IBRBIN=$IBRDIR/bin
IBRTEST=$IBRDIR/test
LIB=$IBRDIR/lib
LIBJAR=$LIB/bin/:$LIB/jxl.jar:$LIB/jgrapht-core-1.2.0.jar:$LIB/log4j-core.jar:$LIB/log4j.jar:$LIB/metouia.jar:$LIB/mysql.jar:$LIB/ojdbc14_g.jar:$LIB/openjgraph.jar:$LIB/postgresql.jar:$LIB/skinlf.jar:$LIB/junit-4.10.jar:$LIB/aima-core.jar
IBRCLASSPATH=$IBRDIR:$LIBJAR
IBR=/edu/uct/ibr

javac -g:none -d $IBRBIN  -sourcepath $IBRSRC -cp $IBRCLASSPATH $IBRSRC/$IBR/*.java $IBRSRC/$IBR/gui/*.java $IBRSRC/$IBR/implication/*.java $IBRSRC/$IBR/util/*.java

javac -g:none -d $IBRBIN -sourcepath $IBRSRC -cp $IBRCLASSPATH $IBRTEST/edu/uct/ibrtest/*.java

javadoc -d ./doc/ -sourcepath $IBRSRC -cp $IBRCLASSPATH -subpackages edu.uct.ibr 