#!/bin/bash
# Build script by: Luke Neville

# To run, ensure user has execute privileges and run ./ibn

if [ "$IBNDIR" == "" ]; then
IBNDIR=.
fi

IBNBIN=$IBNDIR/bin
LIB=/home/luke/Honours/Project/JavaIBN/lib
LIBJAR=$LIB/bin/:$LIB/jxl.jar:$LIB/log4j-core.jar:$LIB/log4j.jar:$LIB/metouia.jar:$LIB/mysql.jar:$LIB/ojdbc14_g.jar:$LIB/openjgraph.jar:$LIB/postgresql.jar:$LIB/skinlf.jar
IBNCLASSPATH=$IBNDIR:$IBNBIN:$LIBJAR

java -cp $IBNCLASSPATH edu.uct.ibn.IBN
