#!/bin/bash
# Build script by: Luke Neville

# To run, ensure user has execute privileges and run ./dbr

if [ "$DBRDIR" == "" ]; then
DBRDIR=.
fi

DBRTEST=$DBRDIR/test
DBRBIN=$DBRDIR/bin
LIB=/home/luke/Honours/Project/JavaDBR/lib
LIBJAR=$LIB/bin/:$LIB/jxl.jar:$LIB/log4j-core.jar:$LIB/log4j.jar:$LIB/metouia.jar:$LIB/mysql.jar:$LIB/ojdbc14_g.jar:$LIB/openjgraph.jar:$LIB/postgresql.jar:$LIB/skinlf.jar
DBRCLASSPATH=$DBRDIR:$DBRBIN:$LIBJAR

java -cp $DBRCLASSPATH edu.uct.dbrtest.testdbr
